version: "3.7"
services:
  mongodb:
    container_name: teste_mongodb
    image: mongo:4.2.3-bionic
    environment:
      MONGO_INITDB_DATABASE: db-local
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb/mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
    # comment to enable mongodb logging
    logging:
      driver: none
